apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    {{- include "job-scanner.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - port: {{ .Values.apiGateway.port }}
      targetPort: {{ .Values.apiGateway.port }}
      nodePort: {{ .Values.apiGateway.nodePort }}
