apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
    {{- include "job-scanner.labels" . | nindent 4 }}
spec:
  selector:
    app: auth-service
  ports:
    - port: {{ .Values.authService.port }}
      targetPort: {{ .Values.authService.port }}
