apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
    {{- include "job-scanner.labels" . | nindent 4 }}
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
