apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  labels:
    app: opensearch
    {{- include "job-scanner.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      initContainers:
        - name: sysctl
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2.13.0
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
            - name: DISABLE_SECURITY_PLUGIN
              value: "true"
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms256m -Xmx256m"
          livenessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /_cluster/health?wait_for_status=yellow
              port: 9200
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
            limits:
              cpu: 700m
              memory: 1Gi
