apiVersion: v1
kind: Service
metadata:
  name: opensearch
  labels:
    app: opensearch
    {{- include "job-scanner.labels" . | nindent 4 }}
spec:
  selector:
    app: opensearch
  ports:
    - port: 9200
      targetPort: 9200
