apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    {{- include "job-scanner.labels" . | nindent 4 }}
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
