apiVersion: v1
kind: ConfigMap
metadata:
  name: scan-service-config
  labels:
    app: scan-service
    {{- include "job-scanner.labels" . | nindent 4 }}
data:
  SERVER_PORT: {{ .Values.scanService.port | quote }}
  DB_HOST: {{ .Values.postgres.host | quote }}
  DB_PORT: {{ .Values.postgres.port | quote }}
  DB_NAME: "scandb"
  DB_USERNAME: {{ .Values.postgres.username | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
  APP_JOB_PROVIDER: {{ .Values.scanService.jobProvider | quote }}
  APIFY_ACTOR_ID: {{ .Values.scanService.apifyActorId | quote }}
  SCAN_SCHEDULER_ENABLED: {{ .Values.scanService.schedulerEnabled | quote }}
  SCAN_SCHEDULER_INTERVAL_MS: {{ .Values.scanService.schedulerIntervalMs | quote }}
