apiVersion: v1
kind: Service
metadata:
  name: scan-service
  labels:
    app: scan-service
    {{- include "job-scanner.labels" . | nindent 4 }}
spec:
  selector:
    app: scan-service
  ports:
    - port: {{ .Values.scanService.port }}
      targetPort: {{ .Values.scanService.port }}
