apiVersion: v1
kind: Service
metadata:
  name: scoring-service
  labels:
    app: scoring-service
    {{- include "job-scanner.labels" . | nindent 4 }}
spec:
  selector:
    app: scoring-service
  ports:
    - port: {{ .Values.scoringService.port }}
      targetPort: {{ .Values.scoringService.port }}
