apiVersion: v1
kind: ConfigMap
metadata:
  name: search-service-config
  labels:
    app: search-service
    {{- include "job-scanner.labels" . | nindent 4 }}
data:
  SERVER_PORT: {{ .Values.searchService.port | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
  APP_SEARCH_INDEX: {{ .Values.searchService.searchIndex | quote }}
  OPENSEARCH_HOST: {{ .Values.opensearch.host | quote }}
  OPENSEARCH_PORT: {{ .Values.opensearch.port | quote }}
  OPENSEARCH_SCHEME: {{ .Values.opensearch.scheme | quote }}
  OPENSEARCH_USERNAME: {{ .Values.opensearch.username | quote }}
